> install.packages('Rcpp', dependencies = TRUE)
> install.packages('ggplot2', dependencies = TRUE)
> install.packages('data.table', dependencies = TRUE)
> install.packages("Hmisc")
> install.packages("forecast")
> library(Hmisc)
> library(forecast)
> library(readxl)
> IPCA.df<-read_excel("c:/Econometria/IPCA.xls")
> plot(IPCA.df$IPCA, type = "l")
> MM <- data.frame(na.omit(ma(IPCA.df$IPCA,order = 12, centre = T)))
> a <- (127-nrow(MM))+1
> IPCA.DF <- as.data.frame(IPCA.df$IPCA[a:127])
> Tabela1 <- cbind(IPCA.DF,MM)
> colnames(Tabela1) <- c("IPCA","Média Móvel")
> View(Tabela1)
> Grafico <- ts(Tabela1, start = 2008, frequency = 12)
> plot(Grafico, plot.type= "single", col=c("Black","Blue"))
> z <- lm(IPCA.df$IPCA~IPCA.df$Ano.M�s)
> abline(z, col="Pink")
> summary(z)
> tabela2 <- as.data.frame(Tabela1$IPCA/Tabela1$`Média Móvel`)
> plot(tabela2)
> Inflacao <- ts(IPCA.df$IPCA, start = 2008, frequency = 12)
> decomposicao <- decompose(Inflacao)
> plot(decompose(Inflacao))
> Tendencia <- decomposicao$trend
> Sazonalidade <- decomposicao$seasonal
> Ciclo <- decomposicao$random
> Tab_Dados1 <- data.frame(IPCA.df$IPCA, Ciclo)
> View(Tab_Dados1)
> plot(Sazonalidade, type="l")
> Serie_Tempo1 <- ts(Tab_Dados1, start = 2008, frequency = 12)
> plot(Serie_Tempo1, plot.type = "single", col= c("Blue", "Red"))
> Tab_Dados2 <- data.frame(IPCA.df$IPCA, Tendencia)
> Serie_Tempo2 <- ts(Tab_Dados2, start = 2008, frequency = 12)
> plot(Serie_Tempo2, plot.type = "single", col= c("Blue", "Red"))